### ISSUE TITLE
Nova rank bugged

### ISSUE THREAD

**Issue by Qaz1337** [NebulaMC-GG/Support#1305]
Store says 2 additional sethomes so 1+2=3 but you get only 2 sethomes ing.
Dosent give you the 25k
/redeem gui) does not work ing or is wrong command at the store

ign soypatoshido
server orion
(for the missing 25k)

**Comment by Qaz1337** [comment]
i deleted the pull requests cos i learned how to use github as forum xD

**Comment by Rasgnarok** [comment]
Fixed, thank you for the report!

**Comment by Qaz1337** [comment]
still missing the 25k, saw staff fly over me so i guess they tried to give me the 25k but i still have only 10k unless coins is some different currency than the pokedollars
